### ISSUE TITLE
16-bit png support

### ISSUE THREAD

**Issue by QuadStorm** [Meshiest/heightmap2brz#4]
It'd be nice to be able to output heightmaps with a large vertical range smoothly.

**Comment by Meshiest** [comment]
I'm thinking about just using the RGBA values as an unsigned integer (`r<<24 | b<<16 | g<<8 | a`)  for more resolution but no one seems to have heightmaps that detailed anywhere

the Rust image library I'm using doesn't support 16bit color so this may not be an option

**Comment by QuadStorm** [comment]
Only issue I would have with that is how to convert a 16 bit png heightmap I already have into that format.

**Comment by qoh** [comment]
> the Rust image library I'm using doesn't support 16bit color so this may not be an option

Are you sure it doesn't support 16-bit color?

[The docs](https://docs.rs/image/0.23.4/image/enum.ColorType.html) mention `ColorType::Rgba16`.

**Comment by Meshiest** [comment]
Guess I can't read! I'll add 16 bit color eventually. For now, multiple 8 bit pngs are now supported

**Comment by Meshiest** [comment]
the [dynamic image docs](https://docs.rs/image/0.19.0/image/enum.DynamicImage.html) that I'm currently using doesn't support 16 bit color out of the box
